### ISSUE TITLE
Makefile:9: recipe for target 'make' failed make: *** [make] Error 1

### ISSUE THREAD

**Issue by ikedashin5** [alessandrofrancesconi/gimp-plugin-bimp#266]
I try to install bimp for my Gimp2.8,but I couldn't success yet.Could someone help me?
My sistem is Linux distro Peppermint10.
 At first I downloaded bimp(gimp-plugin-bimp-master) and extracted it.

Next,I installed libgimp2.0-dev and libpcre3-dev packages. 
Then I got into the "gimp-plugin-bimp-master" directory and put following commands for terminal.

$ make && make install 

following answer was appeared but I can't understand.
I tryed another bimp as 
gimp-plugin-bimp-2.0 and gimp-plugin-bimp-2.5
but the resalts are same.
Can someone tell me what do I have to do?

which gimptool-2.0 && \
gcc -o ./bin/bimp -O2 -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gimp-2.0 -Wall -Wno-unused-variable -Wno-pointer-sign -DGIMP_DISABLE_DEPRECATED src/*.c src/manipulation-gui/*.c src/images/*.c -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lm
/usr/bin/gimptool-2.0
src/bimp-manipulations-gui.c: In function ‘bimp_open_editwindow’:
src/bimp-manipulations-gui.c:48:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_resize_save;
              ^
src/bimp-manipulations-gui.c:52:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_crop_save;
              ^
src/bimp-manipulations-gui.c:56:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_fliprotate_save;
              ^
src/bimp-manipulations-gui.c:60:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_color_save;
              ^
src/bimp-manipulations-gui.c:64:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_sharpblur_save;
              ^
src/bimp-manipulations-gui.c:68:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_changeformat_save;
              ^
src/bimp-manipulations-gui.c:72:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_watermark_save;
              ^
src/bimp-manipulations-gui.c:76:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_rename_save;
              ^
src/bimp-manipulations-gui.c:80:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         save = &bimp_userdef_save;
              ^
src/bimp-operate.c: In function ‘apply_resize’:
src/bimp-operate.c:510:13: error: ‘GIMP_LAYER_MODE_NORMAL_LEGACY’ undeclared (first use in this function)
             GIMP_LAYER_MODE_NORMAL_LEGACY
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bimp-operate.c:510:13: note: each undeclared identifier is reported only once for each function it appears in
src/bimp-operate.c:528:37: error: ‘GIMP_FILL_BACKGROUND’ undeclared (first use in this function); did you mean ‘GIMP_OFFSET_BACKGROUND’?
         gimp_drawable_fill(layerId, GIMP_FILL_BACKGROUND);
                                     ^~~~~~~~~~~~~~~~~~~~
                                     GIMP_OFFSET_BACKGROUND
src/bimp-operate.c:532:9: warning: implicit declaration of function ‘gimp_item_transform_translate’; did you mean ‘gimp_item_transform_rotate’? [-Wimplicit-function-declaration]
         gimp_item_transform_translate(layerId, -abs(view_w - final_w) / 2, -abs(view_h - final_h) / 2);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         gimp_item_transform_rotate
src/bimp-operate.c: In function ‘apply_color’:
src/bimp-operate.c:661:23: warning: implicit declaration of function ‘gimp_drawable_brightness_contrast’; did you mean ‘gimp_brightness_contrast’? [-Wimplicit-function-declaration]
             success = gimp_drawable_brightness_contrast(
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       gimp_brightness_contrast
src/bimp-operate.c:678:23: warning: implicit declaration of function ‘gimp_drawable_levels_stretch’; did you mean ‘gimp_levels_stretch’? [-Wimplicit-function-declaration]
             success = gimp_drawable_levels_stretch(out->drawable_ids[i]);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       gimp_levels_stretch
src/bimp-operate.c:704:31: warning: implicit declaration of function ‘gimp_drawable_curves_spline’; did you mean ‘gimp_drawable_set_pixel’? [-Wimplicit-function-declaration]
                     success = gimp_drawable_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_VALUE, colorcurve_num_points_v, colorcurve_ctr_points_v);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                               gimp_drawable_set_pixel
src/bimp-operate.c: In function ‘image_save’:
src/bimp-operate.c:1101:17: error: ‘GIMP_CONVERT_DITHER_FS’ undeclared (first use in this function); did you mean ‘GIMP_FIXED_DITHER’?
                 GIMP_CONVERT_DITHER_FS,
                 ^~~~~~~~~~~~~~~~~~~~~~
                 GIMP_FIXED_DITHER
src/bimp-operate.c:1102:17: error: ‘GIMP_CONVERT_PALETTE_GENERATE’ undeclared (first use in this function); did you mean ‘GIMP_TYPE_CONVERT_PALETTE_TYPE’?
                 GIMP_CONVERT_PALETTE_GENERATE,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 GIMP_TYPE_CONVERT_PALETTE_TYPE
src/bimp-operate.c: In function ‘image_save_gif’:
src/bimp-operate.c:1178:9: error: ‘GIMP_CONVERT_DITHER_FS’ undeclared (first use in this function); did you mean ‘GIMP_FIXED_DITHER’?
         GIMP_CONVERT_DITHER_FS,
         ^~~~~~~~~~~~~~~~~~~~~~
         GIMP_FIXED_DITHER
src/bimp-operate.c:1179:9: error: ‘GIMP_CONVERT_PALETTE_GENERATE’ undeclared (first use in this function); did you mean ‘GIMP_TYPE_CONVERT_PALETTE_TYPE’?
         GIMP_CONVERT_PALETTE_GENERATE,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         GIMP_TYPE_CONVERT_PALETTE_TYPE
src/bimp-utils.c: In function ‘get_bimp_localedir’:
src/bimp-utils.c:172:5: warning: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Wunused-result]
     readlink("/proc/self/exe", path, bufsize);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:9: recipe for target 'make' failed
make: *** [make] Error 1

**Comment by scribblemaniac** [comment]
Upgrade to GIMP 2.10. The latest version of BIMP will not work with version 2.8.

**Comment by ikedashin5** [comment]
Yes,I already tryed it with same way. The Terminal gave me following message. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Package lcms2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lcms2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'lcms2', required by 'babl', not found
No output from 'pkg-config --cflags gimpui-2.0'
which gimptool-2.0 && \
gcc -o ./bin/bimp -O2 -Wall -Wno-unused-variable -Wno-pointer-sign -DGIMP_DISABLE_DEPRECATED src/*.c src/manipulation-gui/*.c src/images/*.c -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lm
/usr/bin/gimptool-2.0
src/bimp-gui.c:5:10: fatal error: gtk/gtk.h: そのようなファイルやディレクトリはありません
#include <gtk/gtk.h>
^~~~~~~~~~~
compilation terminated.
src/bimp-manipulations-gui.c:5:10: fatal error: gtk/gtk.h: そのようなファイルやディレクトリはありません
#include <gtk/gtk.h>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
and so on
I couldn't understand these message.I had searched on web several days but couldn't get the answer.
Hence I uninstalled Gimp2.10 and try Gimp2.8 ,because I thought it's easyer.

**Comment by scribblemaniac** [comment]
Looks like you might be missing lcms2. Do you have the dev package for that installed?

**Comment by ikedashin5** [comment]
Sorry I'm just a beginner,I don't know what is lcms2 and dev package.Could you tell me what they are and how to get it.
The reason why I gave up Gimp2.10 is in this website.
https://www.dedoimedo.com/computers/gimp-bimp.html
I thought it's too hard for me, then I uninstalled Gimp2.10 
But  I'd like to install it again if I can,

**Comment by scribblemaniac** [comment]
> Sorry I'm just a beginner,I don't know what is lcms2 and dev package.Could you tell me what they are and how to get it.

Just use `sudo apt search <library_name>`, replacing <library_name> with the name of the library that you are looking for to find the name of the package for it. In this case it's probably just called lcms2-dev, but the exact names can vary from distro-to-distro so it's good to check. Then use `sudo apt install <package_name>` to install it.

**Comment by ikedashin5** [comment]
Thank you !  I will going to try . I think to have to get Gimp2.10 again.

**Comment by ikedashin5** [comment]
I used the command

sudo apt search lcms2-dev

The answer was

ソート中... 完了(Sorting ... Done)
全文検索... 完了  (Full-text search ... Done)
liblcms2-dev/bionic-updates,bionic-security 2.9-1ubuntu0.1 amd64
  Little CMS 2 color management library development headers

Next I used

sudo apt install Package lcms2

The answer was

パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
E: パッケージ Package が見つかりません
E: パッケージ lcms2 が見つかりません
as
Loading package list ... Done
Creating a dependency tree
Reading status information ... Done
E: Package Package not found
E: Package lcms2 not found

I tryed to use as

sudo apt install Package liblcms2

But the answer was same.

パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
E: パッケージ Package が見つかりません
E: パッケージ liblcms2 が見つかりません
as
Loading package list ... Done
Creating a dependency tree
Reading status information ... Done
E: Package Package not found
E: Package liblcms2 not found

Did I do something wrong ?
What can I do next?

**Comment by ikedashin5** [comment]
I've got the answer.I had to use BIMP1.18. I used it then I successed!
